global:
  resolve_timeout: 30s

route:
  group_by: ['alertname']
  receiver: 'auto-heal'

receivers:
  - name: 'auto-heal'
    webhook_configs:
      - url: 'http://host.docker.internal:9000/hooks/nginx_recover'
        send_resolved: true

