---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Restart NGINX container
      shell: docker restart nginx-svc
      register: result

    - name: Show restart output
      debug:
        var: result.stdout
